disp(['Add the paths of the different toolboxes... '])
addpath('../Preprocessing_tools')
addpath('../Visualization_tools')
addpath('../Nesting_tools')
addpath('../m_map')
addpath('../air_sea')
addpath('../mask')
addpath('../COADS05')
addpath('../WOA2001')
addpath('../SST_pathfinder')
addpath('../Aforc_bulk')
addpath('../Aforc_NCEP')
addpath('../Aforc_QuikSCAT')
addpath('../Oforc_ECCO')
addpath('../Oforc_SODA')
addpath('../Tides')
addpath('../Diagnostic_tools')
addpath('../netcdf_matlab')
addpath('../netcdf_matlab/ncfiles')
addpath('../netcdf_matlab/nctype')
addpath('../netcdf_matlab/ncutility')
addpath('../DIAGS_spectra')

